Simplified edge to edge
google-developer-training/basic-android-kotlin-compose-training-superheroes pull request #14
Opened 2023-06-29 18:28 UTC by android-dev-lxl

This is the reference PR from Meghan: [Woof edge to edge](https://github.com/google-developer-training/basic-android-kotlin-compose-training-woof/pull/46)

Changes in this PR: 

- Simplified the code a bit
- Removed the code for lower SDK versions since the minimum SDK we support is 24
- Replaced the deprecated APIs with alternative APIs
- Tested the UI on multiple emulator versions, here are screenshots from API versions 25 and 26.

| Original code API 25   | Updated code API 25 |
| ----------- | ----------- |
| <img src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-superheroes/assets/24260141/309b74ef-773a-48bf-806a-62bfdb348dca" width=50% height=50%> |    <img src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-superheroes/assets/24260141/83621095-1435-437c-8a40-264764af211c" width=50% height=50%>    |

| Original code API 26   | Updated code API 26 |
| ----------- | ----------- |
| <img src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-superheroes/assets/24260141/057a2cdd-02fd-4b2f-b5c8-96821b564537" width=50% height=50%> |    <img src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-superheroes/assets/24260141/96e238cf-cc9a-4cf8-95f1-fd83ce439850" width=50% height=50%>    |

 I would appreciate it if you could take a look at these changes and let me know if they are okay.

2023-07-05 16:09 UTC, yenerm requested changes

2023-07-05 16:09 UTC, yenerm commented on app/src/main/java/com/example/superheroes/HeroesScreen.kt
> +    ) {
i think indentation is wrong

2023-07-05 16:09 UTC, yenerm commented on app/src/main/java/com/example/superheroes/ui/theme/Theme.kt
> +            setUpEdgeToEdge(view,darkTheme)
leave space before darkTheme

2023-07-12 18:34 UTC, MagicalMeghan reviewed
LGTM for e2e in Theme.kt file

2023-07-12 22:51 UTC, yaraki approved these changes

2023-08-09 10:58 UTC, johnshea approved these changes
LGTM with two quick fixes needed.

2023-08-09 10:58 UTC, johnshea commented on app/src/main/java/com/example/superheroes/MainActivity.kt
Review unused padding import.
Remove extra newline at EOF.

2023-08-29 14:39 UTC, johnshea requested changes
Update gradle wrapper to latest version. Currently `8.2`
Update `kotlinCompilerExtensionVersion` to the latest.
Update BOM to the latest.
Project build.gradle.kts - Update all plugins to the latest versions

Type.kt - ln 31 - insert blank line to push comment down
Type.kt - ln 33 & ln 41 - remove blank lines for consistency

2023-08-29 14:39 UTC, johnshea commented on app/src/main/java/com/example/superheroes/HeroesScreen.kt
Should the MaterialTheme shape value be used here?
<img width="555" alt="Screenshot 2023-08-29 at 10 10 17 AM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-superheroes/assets/7107817/d6e9a1ba-5413-4586-87a1-071cd0010d04">

2023-08-29 14:39 UTC, johnshea commented on app/src/main/java/com/example/superheroes/HeroesScreen.kt
There are multiple occurences of `72.dp` and `8.dp`.

Can these be moved to the `dimens.xml`?

2023-08-29 16:37 UTC, android-dev-lxl commented on app/src/main/java/com/example/superheroes/HeroesScreen.kt
Yes, this was already reviewed by SMEs

2023-08-29 17:55 UTC, android-dev-lxl commented on app/src/main/java/com/example/superheroes/HeroesScreen.kt
There is no dimens.xml for this project.

2023-08-29 17:55 UTC, android-dev-lxl commented on app/src/main/java/com/example/superheroes/HeroesScreen.kt
Not adding for consistency.

2023-08-31 17:11 UTC, johnshea approved these changes
One nit - build.gradle.kts - You updated to a newer version but didn't update to the latest one.

2023-08-31 17:11 UTC, johnshea commented on build.gradle.kts
> +    id("org.jetbrains.kotlin.android") version "1.9.0" apply false
nit: This isn't the latest version. Latest is `1.9.10`.

2023-09-11 23:20 UTC, merged