Edge to Edge new api
google-developer-training/basic-android-kotlin-compose-training-superheroes pull request #16
Opened 2023-11-08 16:56 UTC by android-dev-lxl

2023-11-13 22:32 UTC, johnshea approved these changes
lgtm

2023-11-24 15:04 UTC, Jaehwa-Noh requested changes
Hello, I'd found your PR as study new edge-to-edge, and I suggested some changes at your code to work properly.

2023-11-24 15:04 UTC, Jaehwa-Noh commented on app/src/main/java/com/example/superheroes/ui/theme/Theme.kt
> +            window.statusBarColor = colorScheme.primary.toArgb()
```suggestion
            window.statusBarColor = Color.Transparent.toArgb()
```
You need to make status bar color transparency.

2023-11-24 15:04 UTC, Jaehwa-Noh commented on app/src/main/java/com/example/superheroes/ui/theme/Theme.kt
> +            WindowCompat.getInsetsController(window, view).isAppearanceLightStatusBars = darkTheme
```suggestion
            WindowCompat.getInsetsController(window, view).isAppearanceLightStatusBars = !darkTheme
```
Need to not operation at darkTheme to show the status information: time, battery, etc.

2023-11-25 00:12 UTC, Jaehwa-Noh commented on app/src/main/java/com/example/superheroes/MainActivity.kt
> +        enableEdgeToEdge()
According this [documentation](https://developer.android.com/jetpack/compose/layouts/insets#compose-apis) 
I think that enableEdgeToEdge() should be placed after super.onCreate(savedInstanceState)

![스크린샷 2023-11-25 091112](https://github.com/google-developer-training/basic-android-kotlin-compose-training-superheroes/assets/48680511/8d8ce27f-083c-438e-9b09-781cd120082a)

2024-03-05 22:33 UTC, yenerm approved these changes

2024-03-05 23:37 UTC, Jaehwa-Noh approved these changes
Thank you to accept my suggestion.
Look good to me!

2024-03-05 23:47 UTC, merged